### ISSUE TITLE
audio sounds stop after a while and then resumes

### ISSUE THREAD

**Issue by nicktheuser123** [MaxAFriedrich/EMDR#7]
using the below url to test
https://emdr.mfriedrich.win/

set the speed to 20 and sets and time to infinity. Enable sound
After about 15-17 seconds the audio goes off for a while.

Any idea why this could be happening?

**Comment by MaxAFriedrich** [comment]
fixed by @nicktheuser123  with pr https://github.com/MaxAFriedrich/EMDR/pull/8
